name: oi-drupal-site
recipe: drupal11
config:
  via: apache:2.4
  database: mariadb:10.11
  composer_version: '2'
  php: '8.4'
  webroot: web
  # xdebug: false
  # config:
    # php: .vscode/php.ini

services:
  appserver:
    overrides:
      environment:
        # ENVIRONMENT: "local"
        # PHP_IDE_CONFIG: "serverName=appserver"
        # PHP_MEMORY_LIMIT: "2G"
        # PHP_CLI_MEMORY_LIMIT: "2G"
  redis:
    type: redis:7
    portforward: true
    persist: true
  phpmyadmin:
    type: phpmyadmin:5.2
  solr:
    type: solr:9.0
    core: openinnovations
    portforward: true
    config:
      conf: solr/conf

proxy:
  solr:
    - search.oi-drupal-site.lndo.site:8983

tooling:
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpstan:
    service: appserver
    cmd: /app/vendor/bin/phpstan
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/unit    

# env_file:
#  - .vscode/lando.env
